export interface OrderRecord {
  id: string
  orderDate: string
  orderStatus: string
  orderType: "RX" | "Pre-Order" | "Standard"
  orderNo: string
  bpCode: string
  bpName: string
  storeCode: string
  storeName: string
  customerName: string
  customerEmail: string
  itemCount: number
  totalAmount: number
  currency: string
  paymentMethod: string
  shippingMethod: string
  requestDate: string
  createdBy: string
}

export interface OrderItem {
  id: string
  itemCode: string
  itemName: string
  color: string
  size: string
  quantity: number
  unitPrice: number
  totalPrice: number
  category: string
  subcategory: string
  status: string
}

export interface OrderDetailData {
  order: OrderRecord
  items: OrderItem[]
}

export const orderRecords: OrderRecord[] = [
  {
    id: "1",
    orderDate: "2026-03-30 16:12 (EST)",
    orderStatus: "Delivered",
    orderType: "RX",
    orderNo: "ORD-2026-00451",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "John Smith",
    customerEmail: "john.smith@email.com",
    itemCount: 3,
    totalAmount: 450.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-30 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "2",
    orderDate: "2026-03-29 15:48 (EST)",
    orderStatus: "Processing",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00450",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1002",
    storeName: "US_STORE_02",
    customerName: "Emily Johnson",
    customerEmail: "emily.j@email.com",
    itemCount: 2,
    totalAmount: 280.00,
    currency: "USD",
    paymentMethod: "PayPal",
    shippingMethod: "Standard",
    requestDate: "2026-03-29 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "3",
    orderDate: "2026-03-29 15:40 (EST)",
    orderStatus: "Pending",
    orderType: "RX",
    orderNo: "ORD-2026-00449",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "Michael Brown",
    customerEmail: "m.brown@email.com",
    itemCount: 1,
    totalAmount: 120.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-29 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "4",
    orderDate: "2026-03-28 10:30 (EST)",
    orderStatus: "Shipped",
    orderType: "Standard",
    orderNo: "ORD-2026-00448",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1001",
    storeName: "CA_STORE_01",
    customerName: "Sarah Williams",
    customerEmail: "s.williams@email.com",
    itemCount: 5,
    totalAmount: 720.00,
    currency: "CAD",
    paymentMethod: "Credit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-28 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "5",
    orderDate: "2026-03-28 09:15 (EST)",
    orderStatus: "Confirmed",
    orderType: "RX",
    orderNo: "ORD-2026-00447",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1003",
    storeName: "US_STORE_03",
    customerName: "David Lee",
    customerEmail: "d.lee@email.com",
    itemCount: 2,
    totalAmount: 340.00,
    currency: "USD",
    paymentMethod: "Debit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-28 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "6",
    orderDate: "2026-03-27 14:22 (EST)",
    orderStatus: "Delivered",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00446",
    bpCode: "C1004",
    bpName: "JP Corporation",
    storeCode: "JP1001",
    storeName: "JP_STORE_01",
    customerName: "Yuki Tanaka",
    customerEmail: "y.tanaka@email.com",
    itemCount: 4,
    totalAmount: 56000,
    currency: "JPY",
    paymentMethod: "Bank Transfer",
    shippingMethod: "Standard",
    requestDate: "2026-03-27 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "7",
    orderDate: "2026-03-27 11:05 (EST)",
    orderStatus: "Canceled",
    orderType: "Standard",
    orderNo: "ORD-2026-00445",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1004",
    storeName: "US_ONLINE",
    customerName: "Jessica Davis",
    customerEmail: "j.davis@email.com",
    itemCount: 1,
    totalAmount: 89.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-27 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "8",
    orderDate: "2026-03-26 16:45 (EST)",
    orderStatus: "Returned",
    orderType: "RX",
    orderNo: "ORD-2026-00444",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1002",
    storeName: "CA_STORE_02",
    customerName: "Robert Wilson",
    customerEmail: "r.wilson@email.com",
    itemCount: 2,
    totalAmount: 310.00,
    currency: "CAD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-26 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "9",
    orderDate: "2026-03-26 13:30 (EST)",
    orderStatus: "Processing",
    orderType: "Standard",
    orderNo: "ORD-2026-00443",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "Amanda Martinez",
    customerEmail: "a.martinez@email.com",
    itemCount: 3,
    totalAmount: 195.00,
    currency: "USD",
    paymentMethod: "PayPal",
    shippingMethod: "Standard",
    requestDate: "2026-03-26 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "10",
    orderDate: "2026-03-25 10:18 (EST)",
    orderStatus: "Delivered",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00442",
    bpCode: "C1004",
    bpName: "JP Corporation",
    storeCode: "JP1002",
    storeName: "JP_STORE_02",
    customerName: "Kenji Yamamoto",
    customerEmail: "k.yamamoto@email.com",
    itemCount: 6,
    totalAmount: 98000,
    currency: "JPY",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-25 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "11",
    orderDate: "2026-03-25 09:00 (EST)",
    orderStatus: "Confirmed",
    orderType: "RX",
    orderNo: "ORD-2026-00441",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1002",
    storeName: "US_STORE_02",
    customerName: "Thomas Anderson",
    customerEmail: "t.anderson@email.com",
    itemCount: 1,
    totalAmount: 175.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-25 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "12",
    orderDate: "2026-03-24 17:30 (EST)",
    orderStatus: "Shipped",
    orderType: "Standard",
    orderNo: "ORD-2026-00440",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1001",
    storeName: "CA_STORE_01",
    customerName: "Jennifer Taylor",
    customerEmail: "j.taylor@email.com",
    itemCount: 3,
    totalAmount: 415.00,
    currency: "CAD",
    paymentMethod: "Debit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-24 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "13",
    orderDate: "2026-03-24 14:15 (EST)",
    orderStatus: "Pending",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00439",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1003",
    storeName: "US_STORE_03",
    customerName: "Christopher Moore",
    customerEmail: "c.moore@email.com",
    itemCount: 2,
    totalAmount: 260.00,
    currency: "USD",
    paymentMethod: "PayPal",
    shippingMethod: "Standard",
    requestDate: "2026-03-24 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "14",
    orderDate: "2026-03-23 11:45 (EST)",
    orderStatus: "Delivered",
    orderType: "RX",
    orderNo: "ORD-2026-00438",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "Lisa White",
    customerEmail: "l.white@email.com",
    itemCount: 4,
    totalAmount: 530.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-23 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "15",
    orderDate: "2026-03-23 09:20 (EST)",
    orderStatus: "Processing",
    orderType: "Standard",
    orderNo: "ORD-2026-00437",
    bpCode: "C1004",
    bpName: "JP Corporation",
    storeCode: "JP1001",
    storeName: "JP_STORE_01",
    customerName: "Hiroshi Sato",
    customerEmail: "h.sato@email.com",
    itemCount: 2,
    totalAmount: 34500,
    currency: "JPY",
    paymentMethod: "Bank Transfer",
    shippingMethod: "Standard",
    requestDate: "2026-03-23 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "16",
    orderDate: "2026-03-22 15:55 (EST)",
    orderStatus: "Confirmed",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00436",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1002",
    storeName: "CA_STORE_02",
    customerName: "Daniel Harris",
    customerEmail: "d.harris@email.com",
    itemCount: 3,
    totalAmount: 485.00,
    currency: "CAD",
    paymentMethod: "Credit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-22 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "17",
    orderDate: "2026-03-22 12:10 (EST)",
    orderStatus: "Shipped",
    orderType: "RX",
    orderNo: "ORD-2026-00435",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1004",
    storeName: "US_ONLINE",
    customerName: "Karen Clark",
    customerEmail: "k.clark@email.com",
    itemCount: 1,
    totalAmount: 155.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-22 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "18",
    orderDate: "2026-03-21 10:40 (EST)",
    orderStatus: "Delivered",
    orderType: "Standard",
    orderNo: "ORD-2026-00434",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "James Robinson",
    customerEmail: "j.robinson@email.com",
    itemCount: 5,
    totalAmount: 670.00,
    currency: "USD",
    paymentMethod: "Debit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-21 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "19",
    orderDate: "2026-03-21 08:30 (EST)",
    orderStatus: "Canceled",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00433",
    bpCode: "C1004",
    bpName: "JP Corporation",
    storeCode: "JP1001",
    storeName: "JP_STORE_01",
    customerName: "Akiko Nakamura",
    customerEmail: "a.nakamura@email.com",
    itemCount: 2,
    totalAmount: 28000,
    currency: "JPY",
    paymentMethod: "Bank Transfer",
    shippingMethod: "Standard",
    requestDate: "2026-03-21 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "20",
    orderDate: "2026-03-20 16:20 (EST)",
    orderStatus: "Delivered",
    orderType: "RX",
    orderNo: "ORD-2026-00432",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1002",
    storeName: "US_STORE_02",
    customerName: "Patricia Lewis",
    customerEmail: "p.lewis@email.com",
    itemCount: 3,
    totalAmount: 395.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-20 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "21",
    orderDate: "2026-03-20 13:15 (EST)",
    orderStatus: "Processing",
    orderType: "Standard",
    orderNo: "ORD-2026-00431",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1001",
    storeName: "CA_STORE_01",
    customerName: "Mark Thompson",
    customerEmail: "m.thompson@email.com",
    itemCount: 4,
    totalAmount: 560.00,
    currency: "CAD",
    paymentMethod: "PayPal",
    shippingMethod: "Standard",
    requestDate: "2026-03-20 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "22",
    orderDate: "2026-03-19 11:50 (EST)",
    orderStatus: "Confirmed",
    orderType: "RX",
    orderNo: "ORD-2026-00430",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1003",
    storeName: "US_STORE_03",
    customerName: "Nancy Garcia",
    customerEmail: "n.garcia@email.com",
    itemCount: 1,
    totalAmount: 210.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-19 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "23",
    orderDate: "2026-03-19 09:30 (EST)",
    orderStatus: "Shipped",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00429",
    bpCode: "C1004",
    bpName: "JP Corporation",
    storeCode: "JP1002",
    storeName: "JP_STORE_02",
    customerName: "Takeshi Ito",
    customerEmail: "t.ito@email.com",
    itemCount: 3,
    totalAmount: 45000,
    currency: "JPY",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-19 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "24",
    orderDate: "2026-03-18 14:40 (EST)",
    orderStatus: "Returned",
    orderType: "Standard",
    orderNo: "ORD-2026-00428",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "Steven Hall",
    customerEmail: "s.hall@email.com",
    itemCount: 2,
    totalAmount: 245.00,
    currency: "USD",
    paymentMethod: "Debit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-18 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "25",
    orderDate: "2026-03-18 10:05 (EST)",
    orderStatus: "Delivered",
    orderType: "RX",
    orderNo: "ORD-2026-00427",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1002",
    storeName: "CA_STORE_02",
    customerName: "Michelle Allen",
    customerEmail: "m.allen@email.com",
    itemCount: 4,
    totalAmount: 620.00,
    currency: "CAD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-18 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "26",
    orderDate: "2026-03-17 15:30 (EST)",
    orderStatus: "Pending",
    orderType: "Standard",
    orderNo: "ORD-2026-00426",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1004",
    storeName: "US_ONLINE",
    customerName: "Kevin Young",
    customerEmail: "k.young@email.com",
    itemCount: 1,
    totalAmount: 99.00,
    currency: "USD",
    paymentMethod: "PayPal",
    shippingMethod: "Standard",
    requestDate: "2026-03-17 (EST)",
    createdBy: "monster1437",
  },
  {
    id: "27",
    orderDate: "2026-03-17 11:20 (EST)",
    orderStatus: "Confirmed",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00425",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1001",
    storeName: "US_STORE_01",
    customerName: "Laura King",
    customerEmail: "l.king@email.com",
    itemCount: 2,
    totalAmount: 330.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-17 (EST)",
    createdBy: "uk_Isaac",
  },
  {
    id: "28",
    orderDate: "2026-03-16 13:50 (EST)",
    orderStatus: "Delivered",
    orderType: "RX",
    orderNo: "ORD-2026-00424",
    bpCode: "C1004",
    bpName: "JP Corporation",
    storeCode: "JP1001",
    storeName: "JP_STORE_01",
    customerName: "Mei Suzuki",
    customerEmail: "m.suzuki@email.com",
    itemCount: 3,
    totalAmount: 41000,
    currency: "JPY",
    paymentMethod: "Bank Transfer",
    shippingMethod: "Standard",
    requestDate: "2026-03-16 (EST)",
    createdBy: "uk_B.danny",
  },
  {
    id: "29",
    orderDate: "2026-03-16 09:45 (EST)",
    orderStatus: "Shipped",
    orderType: "Standard",
    orderNo: "ORD-2026-00423",
    bpCode: "C1002",
    bpName: "US Corporation",
    storeCode: "US1002",
    storeName: "US_STORE_02",
    customerName: "Brian Wright",
    customerEmail: "b.wright@email.com",
    itemCount: 2,
    totalAmount: 185.00,
    currency: "USD",
    paymentMethod: "Credit Card",
    shippingMethod: "Standard",
    requestDate: "2026-03-16 (EST)",
    createdBy: "NAMCHO",
  },
  {
    id: "30",
    orderDate: "2026-03-15 16:00 (EST)",
    orderStatus: "Processing",
    orderType: "Pre-Order",
    orderNo: "ORD-2026-00422",
    bpCode: "C1003",
    bpName: "CA Corporation",
    storeCode: "CA1001",
    storeName: "CA_STORE_01",
    customerName: "Sandra Lopez",
    customerEmail: "s.lopez@email.com",
    itemCount: 5,
    totalAmount: 780.00,
    currency: "CAD",
    paymentMethod: "Debit Card",
    shippingMethod: "Express",
    requestDate: "2026-03-15 (EST)",
    createdBy: "monster1437",
  },
]

export const orderDetails: Record<string, OrderDetailData> = Object.fromEntries(
  orderRecords.map((record) => {
    const items: OrderItem[] = Array.from({ length: record.itemCount }, (_, i) => {
      const categories = [
        { category: "Eyewear", subcategory: "Optical Frames", prefix: "EW" },
        { category: "Eyewear", subcategory: "Sunglasses", prefix: "SG" },
        { category: "Lenses", subcategory: "Progressive", prefix: "LP" },
        { category: "Lenses", subcategory: "Single Vision", prefix: "LS" },
        { category: "Accessories", subcategory: "Cases", prefix: "AC" },
        { category: "Accessories", subcategory: "Cleaning Kits", prefix: "CK" },
      ]
      const cat = categories[(parseInt(record.id) + i) % categories.length]
      const colors = ["Black", "Brown", "Gold", "Silver", "Navy", "Tortoise"]
      const sizes = ["S", "M", "L", "XL"]
      const names = [
        "Classic Round Frame",
        "Modern Square Frame",
        "Aviator Style",
        "Cat Eye Frame",
        "Sport Wrap",
        "Vintage Oval",
        "Progressive Lens Set",
        "Single Vision Lens",
        "Premium Hard Case",
        "Microfiber Cloth Set",
      ]
      const qty = 1 + ((parseInt(record.id) + i) % 5)
      const price = [45, 89, 120, 155, 210, 25, 35, 75, 15, 12][(parseInt(record.id) + i) % 10]
      return {
        id: `item-${record.id}-${i + 1}`,
        itemCode: `${cat.prefix}-${String(1000 + parseInt(record.id) * 10 + i).padStart(5, "0")}`,
        itemName: names[(parseInt(record.id) + i) % names.length],
        color: colors[(parseInt(record.id) + i) % colors.length],
        size: sizes[(parseInt(record.id) + i) % sizes.length],
        quantity: qty,
        unitPrice: price,
        totalPrice: price * qty,
        category: cat.category,
        subcategory: cat.subcategory,
        status: record.orderStatus === "Canceled" ? "Canceled" : record.orderStatus === "Returned" ? "Returned" : "Active",
      }
    })
    return [
      record.id,
      { order: record, items } as OrderDetailData,
    ]
  })
)
